version: '3'
services:
  toposoid-sentence-transformer-neo4j:
    image: toposoid-sentence-transformer-neo4j:0.6
    tty: true
    environment:
      - TOPOSOID_GRAPHDB_HOST=neo4j
      - TOPOSOID_GRAPHDB_WEB_HOST=data-accessor-neo4j-web
      - TOPOSOID_GRAPHDB_WEB_PORT=9005
      - TOPOSOID_SENTENCE_PARSER_JP_WEB_HOST=toposoid-sentence-parser-japanese-web
      - TOPOSOID_SENTENCE_PARSER_JP_WEB_PORT=9001
      - TOPOSOID_SENTENCE_PARSER_EN_WEB_HOST=toposoid-sentence-parser-english-web
      - TOPOSOID_SENTENCE_PARSER_EN_WEB_PORT=9007
      - TOPOSOID_COMMON_NLP_JP_WEB_HOST=toposoid-common-nlp-japanese-web
      - TOPOSOID_COMMON_NLP_JP_WEB_PORT=9006
      - TOPOSOID_COMMON_NLP_EN_WEB_HOST=toposoid-common-nlp-english-web
      - TOPOSOID_COMMON_NLP_EN_WEB_PORT=9008
  toposoid-sentence-parser-japanese-web:
    image: toposoid/toposoid-sentence-parser-japanese-web:0.6
    environment:
      - PRIVATE_IP_ADDRESS=toposoid-sentence-parser-japanese-web
      - PLAY_HTTP_PORT=9001
    ports:
      - 9001:9001
  toposoid-common-nlp-japanese-web:
    image: toposoid/toposoid-common-nlp-japanese-web:0.6-lowspec-lowspec
    environment:
      - PRIVATE_IP_ADDRESS=toposoid-common-nlp-japanese-web
      - TOPOSOID_SYNONYM_NOUN_SIMILARITY_THRESHHOLD_JP=0.52
      - TOPOSOID_SYNONYM_VERB_SIMILARITY_THRESHHOLD_JP=0.52
      - TOPOSOID_WORD2VEC_SIMILARITY_THRESHHOLD_JP=0.68
      - TOPOSOID_CHIVE_MODEL_VERSION=chive-1.2-mc90.kv
      - TOPOSOID_SENTENCEBERT_MODEL_JP=sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
      - SENTENCE_TRANSFORMERS_HOME=./models
      - PLAY_HTTP_PORT=9006
    ports:
      - 9006:9006
  toposoid-sentence-parser-english-web:
    image: toposoid/toposoid-sentence-parser-english-web:0.6-lowspec-lowspec
    environment:
      - PRIVATE_IP_ADDRESS=toposoid-sentence-parser-english-web
      - PLAY_HTTP_PORT=9007
      - TOPOSOID_CORENLP_HOST=corenlp
      - TOPOSOID_PARSER_SPACY_MODEL_EN=en_core_web_md
    ports:
      - 9007:9007
  toposoid-common-nlp-english-web:
    image: toposoid/toposoid-common-nlp-english-web:0.6-lowspec-lowspec
    environment:
      - PRIVATE_IP_ADDRESS=toposoid-common-nlp-english-web
      - TOPOSOID_SYNONYM_NOUN_SIMILARITY_THRESHHOLD_EN=0.52
      - TOPOSOID_SYNONYM_VERB_SIMILARITY_THRESHHOLD_EN=0.52
      - TOPOSOID_WORD2VEC_SIMILARITY_THRESHHOLD_EN=0.78
      - TOPOSOID_SPACY_MODEL_EN=en_core_web_md
      - TOPOSOID_SENTENCEBERT_MODEL_EN=sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
      - SENTENCE_TRANSFORMERS_HOME=./models
      - PLAY_HTTP_PORT=9008
    ports:
      - 9008:9008
  corenlp:
    image: toposoid/corenlp:3.4.2-lowspec
    ports:
      - 9000:9000
  neo4j:
    image: neo4j:4.4.23
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,algo.*
      - NEO4J_dbms_memory_heap_initial__size=512m
      - NEO4J_dbms_memory_heap_max__size=2G
      - NEO4J_dbms_transaction_timeout=10s
      - NEO4J_apoc_uuid_enabled=true
      - NEO4J_dbms_default__listen__address=0.0.0.0
      - NEO4J_dbms_allow__upgrade=true
      - NEO4J_dbms_default__database=neo4j
      - NEO4J_AUTH=neo4j/p@ssw0rd
  data-accessor-neo4j-web:
    image: toposoid/data-accessor-neo4j-web:0.6
    environment:
      - PRIVATE_IP_ADDRESS=data-accessor-neo4j-web
      - TOPOSOID_GRAPHDB_HOST=neo4j
      - PLAY_HTTP_PORT=9005
    ports:
      - 9005:9005
