version: '3'
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24
services:
  toposoid-sentence-transformer-neo4j:
    image: toposoid-sentence-transformer-neo4j:0.5-SNAPSHOT
    tty: true
    environment:
      - GRAPHDB_HOST=172.30.0.2
      - TOPOSOID_SENTENCE_PARSER_JP_WEB_HOST=172.30.0.4
      - TOPOSOID_SENTENCE_PARSER_JP_WEB_PORT=9001
      - TOPOSOID_SENTENCE_PARSER_EN_WEB_HOST=172.30.0.6
      - TOPOSOID_SENTENCE_PARSER_EN_WEB_PORT=9007
      - TOPOSOID_COMMON_NLP_JP_WEB_HOST=172.30.0.5
      - TOPOSOID_COMMON_NLP_JP_WEB_PORT=9006
      - TOPOSOID_COMMON_NLP_EN_WEB_HOST=172.30.0.7
      - TOPOSOID_COMMON_NLP_EN_WEB_PORT=9008
    networks:
      app_net:
        ipv4_address: 172.30.0.3
  toposoid-sentence-parser-japanese-web:
    image: toposoid/toposoid-sentence-parser-japanese-web:0.5-SNAPSHOT-workflow
    environment:
      - PRIVATE_IP_ADDRESS=172.30.0.4
      - PLAY_HTTP_PORT=9001
    networks:
      app_net:
        ipv4_address: 172.30.0.4
    ports:
      - 9001:9001
  toposoid-common-nlp-japanese-web:
    image: toposoid/toposoid-common-nlp-japanese-web:0.5-SNAPSHOT-workflow
    environment:
      - PRIVATE_IP_ADDRESS=172.30.0.5
      - SYNONYM_NOUN_SIMILARITY_THRESHHOLD_JP=0.52
      - SYNONYM_VERB_SIMILARITY_THRESHHOLD_JP=0.52
      - WORD2VEC_SIMILARITY_THRESHHOLD_JP=0.68
      - CHIVE_MODEL_VERSION=chive-1.2-mc90.kv
      - TOPOSOID_SENTENCEBERT_MODEL_JP=sentence-transformers/paraphrase-multilingual-mpnet-base-v2
      - PLAY_HTTP_PORT=9006
    networks:
      app_net:
        ipv4_address: 172.30.0.5
    ports:
      - 9006:9006
  toposoid-sentence-parser-english-web:
    image: toposoid/toposoid-sentence-parser-english-web:0.5-SNAPSHOT
    environment:
      - PRIVATE_IP_ADDRESS=172.30.0.6
      - PLAY_HTTP_PORT=9007
      - CORENLP_HOST=172.30.0.8
    networks:
      app_net:
        ipv4_address: 172.30.0.6
    ports:
      - 9007:9007
  toposoid-common-nlp-english-web:
    image: toposoid/toposoid-common-nlp-english-web:0.5-SNAPSHOT
    environment:
      - PRIVATE_IP_ADDRESS=172.30.0.7
      - SYNONYM_NOUN_SIMILARITY_THRESHHOLD_EN=0.52
      - SYNONYM_VERB_SIMILARITY_THRESHHOLD_EN=0.52
      - WORD2VEC_SIMILARITY_THRESHHOLD_EN=0.78
      - TOPOSOID_SENTENCEBERT_MODEL_EN=sentence-transformers/paraphrase-multilingual-mpnet-base-v2
      - PLAY_HTTP_PORT=9008
    networks:
      app_net:
        ipv4_address: 172.30.0.7
    ports:
      - 9008:9008
  corenlp:
    image: toposoid/corenlp:3.4.2-workflow
    networks:
      app_net:
        ipv4_address: 172.30.0.8
    ports:
      - 9000:9000
  neo4j:
    #    container_name: Neo4j-test
    image: neo4j:4.4.23
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,algo.*
      - NEO4J_dbms_memory_heap_initial__size=512m
      - NEO4J_dbms_memory_heap_max__size=2G
      - NEO4J_dbms_transaction_timeout=10s
      - NEO4J_apoc_uuid_enabled=true
      - NEO4J_dbms_default__listen__address=0.0.0.0
      - NEO4J_dbms_allow__upgrade=true
      - NEO4J_dbms_default__database=neo4j
      - NEO4J_AUTH=neo4j/p@ssw0rd
    networks:
      app_net:
        ipv4_address: 172.30.0.2
