version: '3'
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24
services:
  toposoid-sentence-transformer-neo4j:
    image: toposoid-sentence-transformer-neo4j:0.1-SNAPSHOT
    tty: true
    environment:
      - GRAPHDB_HOST=172.30.0.2
      - SENTENCE_PARSER_WEB_HOST=172.30.0.4
      - COMMON_NLP_WEB_HOST=172.30.0.5
    networks:
      app_net:
        ipv4_address: 172.30.0.3
  toposoid-sentence-parser-web:
    image: toposoid/toposoid-sentence-parser-web:0.1-SNAPSHOT
    tty: true
    environment:
      - PRIVATE_IP_ADDRESS=172.30.0.4
      - PLAY_HTTP_PORT=9001
    networks:
      app_net:
        ipv4_address: 172.30.0.4
    ports:
      - 9001:9001
  scala-common-nlp-japanese-web:
    image: toposoid/scala-common-nlp-japanese-web:0.1-SNAPSHOT
    tty: true
    environment:
      - PRIVATE_IP_ADDRESS=172.30.0.5
      - PLAY_HTTP_PORT=9006
    networks:
      app_net:
        ipv4_address: 172.30.0.5
    ports:
      - 9006:9006
  neo4j:
    image: neo4j:4.1.3
    environment:
      - NEO4J_AUTH=neo4j/p@ssw0rd
    ports:
      - 7474:7474
      - 7687:7687
    networks:
      app_net:
        ipv4_address: 172.30.0.2
