version: '3'
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24
services:
  toposoid-sentence-transformer-neo4j:
    image: toposoid-sentence-transformer-neo4j:0.1-SNAPSHOT
    tty: true
    environment:
      - GRAPHDB_HOST=172.30.0.2
      - SENTENCE_PARSER_JP_WEB_HOST=172.30.0.4
      - SENTENCE_PARSER_EN_WEB_HOST=172.30.0.6
      - COMMON_NLP_JP_WEB_HOST=172.30.0.5
      - COMMON_NLP_EN_WEB_HOST=172.30.0.7
    networks:
      app_net:
        ipv4_address: 172.30.0.3
  toposoid-sentence-parser-japanese-web:
    image: toposoid/toposoid-sentence-parser-japanese-web:0.1-SNAPSHOT
    environment:
      - PRIVATE_IP_ADDRESS=172.30.0.4
      - PLAY_HTTP_PORT=9001
    networks:
      app_net:
        ipv4_address: 172.30.0.4
    ports:
      - 9001:9001
  scala-common-nlp-japanese-web:
    image: toposoid/scala-common-nlp-japanese-web:0.1-SNAPSHOT
    environment:
      - PRIVATE_IP_ADDRESS=172.30.0.5
      - PLAY_HTTP_PORT=9006
    networks:
      app_net:
        ipv4_address: 172.30.0.5
    ports:
      - 9006:9006
  toposoid-sentence-parser-english-web:
    image: toposoid/toposoid-sentence-parser-english-web:0.1-SNAPSHOT
    environment:
      - PRIVATE_IP_ADDRESS=172.30.0.6
      - PLAY_HTTP_PORT=9007
      - CORENLP_HOST=172.30.0.8
    networks:
      app_net:
        ipv4_address: 172.30.0.6
    ports:
      - 9007:9007
  scala-common-nlp-english-web:
    image: toposoid/scala-common-nlp-english-web:0.1-SNAPSHOT
    environment:
      - PRIVATE_IP_ADDRESS=172.30.0.7
      - SYNONYM_NOUN_SIMILARITY_THRESHHOLD=0.52
      - SYNONYM_VERB_SIMILARITY_THRESHHOLD=0.52
      - PLAY_HTTP_PORT=9008
    networks:
      app_net:
        ipv4_address: 172.30.0.7
    ports:
      - 9008:9008
  corenlp:
    image: toposoid/corenlp:3.4.2-action
    networks:
      app_net:
        ipv4_address: 172.30.0.8
    ports:
      - 9000:9000
  neo4j:
    image: neo4j:4.1.3
    environment:
      - NEO4J_dbms_transaction_timeout=10s
      - NEO4J_AUTH=neo4j/p@ssw0rd
    ports:
      - 7474:7474
      - 7687:7687
    networks:
      app_net:
        ipv4_address: 172.30.0.2
