FROM toposoid/toposoid-scala-lib-base:0.6

WORKDIR /app
ARG TARGET_BRANCH
ENV DEPLOYMENT=local
ENV _JAVA_OPTIONS="-Xms512m -Xmx4g"

RUN apt-get update \
&& apt-get -y install git \
&& git clone https://github.com/toposoid/scala-data-accessor-neo4j.git \
&& cd scala-data-accessor-neo4j \
&& git pull \
&& git fetch origin ${TARGET_BRANCH} \
&& git checkout ${TARGET_BRANCH} \
&& sbt publishLocal \
&& cd .. \
&& git clone https://github.com/toposoid/toposoid-sentence-transformer-neo4j.git \
&& cd toposoid-sentence-transformer-neo4j \
&& git pull \
&& git fetch origin ${TARGET_BRANCH} \
&& git checkout ${TARGET_BRANCH}
